logging:
  #日志存储地址
  file: "logs/JavaFx-Spring.log"
info:
  name : "入门案例"

server:
  #端口号
  port: 8086
  servlet:
    context-path: /demo

spring:
  kafka:
    bootstrap-servers: localhost:9092

mqtt:
  enable: true
  host: tcp://localhost:1883
  username:
  pwd: